---
# vars file for roles/postgresql
_postgres_packages:
  default:
    - postgresql
    - postgresql-client

postgres_packages: "{{ _postgres_packages['default'] }}"

_postgres_dir:
  default: /var/lib/postgresql/11

postgres_dir: "{{ _postgres_dir['default'] }}"

_postgres_conf_dir:
  default: /etc/postgresql/11/main

postgres_conf_dir: "{{ _postgres_conf_dir['default'] }}"
