---
extends: default
rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
  truthy: disable
  indentation: disable  # This should be enabled, but not run for ignored files
  new-line-at-end-of-file: disable  # This should be enabled
