---
galaxy_info:
  author: Princeton University Library
  description: Dataspace

  license: BSD

  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - 18.04
dependencies:
  - role: 'postgresql'
  - role: 'dspace'
