---
# tasks file for roles/postgresql
#
- name: postgresql key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: Configure upstream APT repository
  apt_repository:
    repo: "{{ postgresql_upstream_repo }}"
    state: present
    update_cache: true

- name: install postgres
  package:
    name: "{{ postgres_packages }}"
    state: present
  register: postgres_install_postgres
  until: postgres_install_postgres is succeeded
  retries: 3

- name: create postgres data directory
  file:
    path: "{{ postgres_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: configure postgres
  lineinfile:
    path: "{{ postgres_conf_dir }}/postgresql.conf"
    regex: "^{{ item.name }} ="
    line: "{{ item.name }} = '{{ item.value }}'"
    create: true
  with_items:
    - "{{ postgres_settings }}"
  when:
    - postgres_settings is defined
  notify:
    - restart postgres
  loop_control:
    label: "{{ item.name }}"

- name: create pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_conf_dir }}/pg_hba.conf"
    backup: true
  notify:
    - reload postgres

- name: start and enable postgres
  service:
    name: postgresql
    state: started
    enabled: true

- name: install psycopg2-binary
  pip:
    name: psycopg2-binary
    state: present
  register: postgres_install_psycopg2_binary
  until: postgres_install_psycopg2_binary is succeeded
  retries: 3
  when:
    - postgres_databases is defined or
      postgres_users is defined

- name: flush handlers
  meta: flush_handlers

- name: create postgres database
  postgresql_db:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ postgres_databases }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_databases is defined
  become_user: postgres
  become: true

- name: create postgres users
  postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db | default(omit) }}"
    password: "{{ item.password }}"
    expires: "{{ item.expires | default(omit) }}"
  with_items:
    - "{{ postgres_users }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_users is defined
  become_user: postgres
  become: true
