---
- name: restart PostgreSQL
  service: name=postgresql state=restarted

- name: create dspace home directory
  file:
    path: "{{ dspace_home }}"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_user }}"

- name: dspace | perform fresh install
  command: /usr/bin/ant fresh_install chdir={{ ant_source_dir }} creates={{ dspace_home }}/webapps/xmlui
  become_user: "{{ project_user }}"
  become: true
  ignore_errors: true

- name: set up tomcat ROOT context
  shell: echo '<Context docBase="{{ dspace_home }}/webapps/xmlui"/>' > /var/lib/tomcat8/conf/Catalina/localhost/ROOT.xml
  become: true

- name: set up other tomcat contexts
  shell: echo '<Context docBase="{{ dspace_home }}/webapps/{{ item }}"/>' > /var/lib/tomcat8/conf/Catalina/localhost/{{ item }}.xml
  with_items:
    - solr
    - oai
    - swordv2
    - sword
  become: true

- name: start tomcat
  service:
    name: tomcat8
    state: restarted
    enabled: true
  become: true
