---
# vars file for dataspace
postgres_databases:
  - name: "{{ project_user }}"
postgres_users:
  - name: "{{ project_user }}"
    password: "{{ project_db_password | default('MyCoMpLeXpAsSwOrD') }}"
    db: "{{ project_user }}"
postgres_hba_entries:
  - type: local
    database: all
    user: all
    method: peer
  - type: host
    database: all
    address: 127.0.0.1/32
    user: all
    method: trust
